services:
  usersservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5025:8080"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=eCommerceDb
      - DATABASE_USER=arvisiljins
      - DATABASE_PASSWORD=xxx111
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - users-network

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=eCommerceDb
      - POSTGRES_USER=arvisiljins
      - POSTGRES_PASSWORD=xxx111
    ports:
      - "5434:5432"
    volumes:
      - users-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arvisiljins -d eCommerceDb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - users-network

volumes:
  users-postgres-data:

networks:
  users-network:
    driver: bridge
